import type { Metadata } from "next";
import { Geist, Geist_Mono, Chivo_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import GlobalLoader from "@/components/GlobalLoader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const chivoMono = Chivo_Mono({
  subsets: ["latin"],
  variable: "--font-chivo-mono",
});

const dreamerTM = localFont({
  src: "../../public/fonts/DreamerTM-Regular.ttf",
  variable: "--font-dreamer",
  weight: "400",
});

const monsterRacing = localFont({
  src: "../../public/fonts/Monster Racing.otf",
  variable: "--font-monster-racing",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${chivoMono.variable} ${dreamerTM.variable} ${monsterRacing.variable} antialiased`}
      >
        <GlobalLoader /> {/* ✅ Always visible above pages */}
        {children}
      </body>
    </html>
  );
}
